# User config
title: "echo_giao的个人博客"
author: "echo_giao"
tagline: "Pineapple Certfied Jekyll Theme"
description: "A personal blog for anything..."
keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "1459181201@qq.com"
linkedin: "https://www.linkedin.com/in/%E4%BD%90%E9%83%9C-%E8%B5%B5-130085392/"
twitter: "https://twitter.com/"
github: "https://github.com/fcb17zzg"

# Site config
url: "https://fcb17zzg.github.io"
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed